#+TITLE:     Interactive Music - Week 2 - Artist Manifesto
#+AUTHOR:    Michael Simpson
#+EMAIL:     mgsimpson@gmail.com
#+OPTIONS: H:2 num:nil toc:nil \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t

* Artist Manifesto

:PROPERTIES: 
:UPDATED: <2017-01-29 Sun>
:RELEASE: 0.0.1
:END:

expression that allows for 

There is a sensation when we experience something so Awesome

"Atmosphere is everything."

I think 

I believe that our environments (micro and macro) play fundamental roles influencing the statee of our human condition. Atmosphere is a conglomeration of the forces around us, real and virtual. Some of these forces are easily apparent, others might be harder to see, woven so deeply into the fabric.

"A Pattern Language"

A Pattern Language

The answer, to me, is to build this thing one part at a time. 
Build things that are extensible and modular.

My quantitative


I want to create atmospheres. By atmospheres, I am referring to spaces in place and time whose features (eg. architecture, light, sound) are contributing or creating  

I hope that my work could be seen as a curation of gestures that reflect my emotion and intention and process that form their foundation.
This document is a work in progress whose evolution will be recorded on github.

I am in pursuit of a technique that allows me to seamlessly combine my multidisciplinary sensibilities and skills into a form of honest expression. The ethos of my work is derivative of my own values/ideas and the inspirations I have found in music, art, contemporary philosophy, architecture/design, and science. Some people who have been remarkably influential to me and my ideas:

** Architecture
*** Christopher Alexander - A Pattern Language, Notes on the Synthesis of Form
*** Peter Zumthor - Atmosphere is everthing.
** Philosophy
*** John Dewey - Pragmatism
----

Additional Inspirations

* Inspirations
** Free Jazz  
*** of territory Organic and allowed to evolve freely.

** A Pattern Language
*** Christopher Alexander
**** Patterns underly everything. There are good patterns and bad patterns. Find the good ones and rely on them.

* Good sensibilities are the foundation for good design, in any medium.

* Lines of Flight
** Gilles Deleuze & Felix Guattari
*** My work is informed by my research and the discovery process is a means to guiding the research.

* Mostly The Voice
** Emotionally touching work, makes people feel good, feel comfortable, feel happy, feel goodsad.

* Organic / Generative
** Form: The context are used to derive the works grammar.

* Adaptive / Free
** I've been inspired by the jazz movement, sample based music .

* Descriptors

* Minimal
* Sharp
* Serene
* Warm
* Infinity
